#!/bin/sh

# This script takes a path to an "images" directory produced by
# one of our buildroot image targets, and wraps up the ext3
# filesystem into a partitioned, bootable hard disk image.
#
# We're using syslinux, so we create a little boot stub partition
# that is VFAT-formatted and contains syslinux.cfg and the bzImage.
# syslinux then boots the kernel with a cmdline telling it to find
# its root filesystem inside the ext3 partition.
#
# Maybe one day we'll use extlinux so we don't need this stub partition,
# but this way is more convenient to do without root since we don't need
# to mount the image to install syslinux into it.

set -eu

ROOT_DIR="$(realpath "$(dirname "$0")/..")"
SYSLINUX_CFG="$ROOT_DIR/config/common/syslinux.cfg"
GENIMAGE_CFG="$ROOT_DIR/config/common/genimage.cfg"

if [ -z "${1-}" ]; then
   echo >&2 "Usage: make-disk-image <output-images-dir>"
   exit 2
fi

IMAGES_DIR="$(realpath $1)"

# Put our toolchain in PATH so we can use the filesystem utilities
# that buildroot has put in there.
export PATH="$ROOT_DIR/toolchain/host/usr/sbin:$ROOT_DIR/toolchain/host/usr/bin:$PATH"

cd "$IMAGES_DIR"

echo "\nCreating hard disk image from partial images in $IMAGES_DIR ...\n"

echo "- Make VFAT boot.img"
dd 2>/dev/null if=/dev/zero of=boot.img bs=16M count=1
mkfs.vfat boot.img

echo "- Install kernel"
mcopy -i boot.img bzImage ::

echo "- Install syslinux"
mcopy -i boot.img "$SYSLINUX_CFG" ::
syslinux -i boot.img

echo "- Generate Hard Disk image disk.img"
mkdir -p genimage-tmp
mkdir -p genimage-root
genimage --config "$GENIMAGE_CFG" --outputpath "$IMAGES_DIR" --inputpath "$IMAGES_DIR" --rootpath "$IMAGES_DIR/genimage-root" --tmppath "$IMAGES_DIR/genimage-tmp"

echo "- Install syslinux MBR"
dd 2>/dev/null conv=notrunc bs=440 count=1 if=syslinux/mbr.bin of=disk.img

echo "\nAll done! $IMAGES_DIR/disk.img should now be a bootable hard disk image.\n"
