#!/bin/sh

# This script takes a path to an "images" directory produced by
# one of our buildroot image targets, and wraps up the ext3
# filesystem into a partitioned, bootable hard disk image.
#
# We're using syslinux, so we create a little boot stub partition
# that is VFAT-formatted and contains syslinux.cfg and the bzImage.
# syslinux then boots the kernel with a cmdline telling it to find
# its root filesystem inside the ext3 partition.
#
# Maybe one day we'll use extlinux so we don't need this stub partition,
# but this way is more convenient to do without root since we don't need
# to mount the image to install syslinux into it.

set -eu

ROOT_DIR="$(realpath "$(dirname "$0")/..")"
GENIMAGE_CFG="$ROOT_DIR/config/common/genimage.cfg"

if [ -z "${2-}" ]; then
   echo >&2 "Usage: make-disk-image <output-images-dir> <xen|qemu>"
   exit 2
fi

IMAGES_DIR="$(realpath $1)"
PLATFORM_TYPE="$2"

SYSLINUX_CFG="$ROOT_DIR/config/common/syslinux-$PLATFORM_TYPE.cfg"
GENIMAGE_CFG="$ROOT_DIR/config/common/genimage-$PLATFORM_TYPE.cfg"

if [ ! -f "$SYSLINUX_CFG" ]; then
   echo >&2 "Unsupported target platform '$PLATFORM_TYPE'"
   exit 2
fi
if [ ! -f "$GENIMAGE_CFG" ]; then
   echo >&2 "Unsupported target platform '$PLATFORM_TYPE'"
   exit 2
fi

BOOT_IMG_NAME="$PLATFORM_TYPE-boot.img"
DISK_IMG_NAME="$PLATFORM_TYPE-disk.img"

# Put our toolchain in PATH so we can use the filesystem utilities
# that buildroot has put in there.
export PATH="$ROOT_DIR/toolchain/host/usr/sbin:$ROOT_DIR/toolchain/host/usr/bin:$PATH"

cd "$IMAGES_DIR"

echo "\nCreating hard disk image from partial images in $IMAGES_DIR ...\n"

echo "- Make VFAT $BOOT_IMG_NAME"
dd 2>/dev/null if=/dev/zero of="$BOOT_IMG_NAME" bs=16M count=1
mkfs.vfat "$BOOT_IMG_NAME"

echo "- Install kernel"
mcopy -i "$BOOT_IMG_NAME" bzImage ::

echo "- Install syslinux"
mcopy -i "$BOOT_IMG_NAME" "$SYSLINUX_CFG" ::syslinux.cfg
syslinux -i "$BOOT_IMG_NAME"

echo "- Generate Hard Disk image $DISK_IMG_NAME"
mkdir -p genimage-tmp
mkdir -p genimage-root
genimage --config "$GENIMAGE_CFG" --outputpath "$IMAGES_DIR" --inputpath "$IMAGES_DIR" --rootpath "$IMAGES_DIR/genimage-root" --tmppath "$IMAGES_DIR/genimage-tmp"

echo "- Install syslinux MBR"
dd 2>/dev/null conv=notrunc bs=440 count=1 if=syslinux/mbr.bin of="$DISK_IMG_NAME"

echo "\nAll done! $IMAGES_DIR/$DISK_IMG_NAME should now be a hard disk image that can be booted by $PLATFORM_TYPE.\n"
